---
title: '615 midterm'
author: "Yu Xia, Ziqing Wang, Bo Zhang"
date: "October 22, 2016"
output: html_document
---

```{r setup, include=FALSE}
library(data.table)
library(reshape2)
library(plyr)
library(ggplot2)
library(stringr)
library(dplyr)
library(maps)
library(mapproj)
```

## Load Data and save as RDS files
```{r}
oilgascounty <- read.csv("~/Desktop/615 midterm/oilgascounty.csv", header=TRUE) # Load raw data
saveRDS(oilgascounty,"oilgas_raw.rds") # Save RDS file

# Delete "county" from column "County_Name":
oilgascounty=mutate(oilgascounty,County_Name=as.character(County_Name)) 
oilgascounty=mutate(oilgascounty,County_Name=sapply(strsplit(oilgascounty$County_Name,split = ' ', fixed = TRUE),function(x) (x[1])))

oilcounty=oilgascounty[, -which(names(oilgascounty) %in% c("gas2000","gas2001","gas2002","gas2003","gas2004","gas2005","gas2006","gas2007","gas2008","gas2009","gas2010","gas2011","gas_change_group","oil_gas_change_group"))] # Create a new subset which only consists of oil productions.
saveRDS(oilcounty,"oilcounty.rds")

gascounty=oilgascounty[, -which(names(oilgascounty) %in% c("oil2000","oil2001","oil2002","oil2003","oil2004","oil2005","oil2006","oil2007","oil2008","oil2009","oil2010","oil2011","oil_change_group","oil_gas_change_group"))] # Create a new subset which only consists of gas productions.
saveRDS(gascounty,"gascounty.rds")
```

## 
```{r}
# 
oilcounty=melt(oilcounty,id.vars = c("FIPS","geoid","Stabr","County_Name","Rural_Urban_Continuum_Code_2013","Urban_Influence_2013","Metro_Nonmetro_2013","Metro_Micro_Noncore_2013","oil_change_group"))
names(oilcounty)[10]="Year"
names(oilcounty)[11]="Oil_Production"

gascounty=melt(gascounty,id.vars = c("FIPS","geoid","Stabr","County_Name","Rural_Urban_Continuum_Code_2013","Urban_Influence_2013","Metro_Nonmetro_2013","Metro_Micro_Noncore_2013","gas_change_group"))
names(gascounty)[10]="Year"
names(gascounty)[11]="Gas_Production"

oilcounty$Year= str_sub(oilcounty$Year,4,7)
gascounty$Year= str_sub(gascounty$Year,4,7)

gassub=subset(gascounty,select = c(gas_change_group,Gas_Production))
ogcounty_clean=cbind(oilcounty,gassub)
oil_gas_change_group=oilgascounty$oil_gas_change_group
ogcounty_clean=cbind(ogcounty_clean,oil_gas_change_group)
ogcounty_clean=ogcounty_clean[,c(1:8,10,11,13,9,12,14)]
ogcounty_clean=ogcounty_clean[,-1]

```

### Visualization
```{r}
# Add oil production of all countys by year
grossoil=unique(aggregate(as.numeric(ogcounty_clean$Oil_Production),by= list(Year=ogcounty_clean$Year),FUN=sum))
names(grossoil)[2]="Oil_Sum"
grossgas=unique(aggregate(as.numeric(ogcounty_clean$Gas_Production),by= list(Year=ogcounty_clean$Year), FUN=sum))
names(grossgas)[2]="Gas_Sum"

ggplot(data=grossoil)+aes(x=Year,y=Oil_Sum,group=1)+geom_path(col="red")+ggtitle("Gross production of Oil")+geom_point()+scale_y_continuous(labels=function(Oil_Sum)Oil_Sum/1000000)+theme(axis.title=element_text(size=10))

ggplot(data=grossgas)+aes(x=Year,y=Gas_Sum,group=1)+geom_path(col="blue")+ggtitle("Gross production of Gas")+geom_point()+scale_y_continuous(labels=function(Gas_Sum)Gas_Sum/1000000)+theme(axis.title=element_text(size=10))

# Plot by type of county (2-Metro, 0-Noncore, 1-Micro)
typecty_oil=aggregate(as.numeric(ogcounty_clean$Oil_Production),by=list(Year=ogcounty_clean$Year,Type=ogcounty_clean$Metro_Micro_Noncore_2013),FUN=sum)
names(typecty_oil)[3]="Oil_Sum"

ggplot(data=typecty_oil,aes(x=Year,y=Oil_Sum))+geom_bar(stat = "identity",aes(fill=Type))+ scale_y_continuous(labels=function(Oil_Sum)Oil_Sum/1000000)+theme(axis.title=element_text(size=10))

typecty_gas=aggregate(as.numeric(ogcounty_clean$Gas_Production),by=list(Year=ogcounty_clean$Year,Type=ogcounty_clean$Metro_Micro_Noncore_2013),FUN=sum)
names(typecty_gas)[3]="Gas_Sum"

ggplot(data=typecty_gas,aes(x=Year,y=Gas_Sum))+geom_bar(stat = "identity",aes(fill=Type))+ scale_y_continuous(labels=function(Gas_Sum)Gas_Sum/1000000)+theme(axis.title=element_text(size=10))

```

